//#define CONFIG_ENABLE_ALERTS
#define CONFIG_ENABLE_STORAGE_MODE
//#define CONFIG_ENABLE_DYNAMIC_BIASING

#ifdef CONFIG_ENABLE_STORAGE_MODE
#  define CONFIG_MAX_STORED_SAMPLES 100
//#  define CONFIG_ENABLE_FLASH_PARAMS //TODO
#endif /* #ifdef CONFIG_ENABLE_STORAGE_MODE */
